package org.krost.unidrive.e2e

import org.krost.unidrive.e2e.verify.HashVerifier
import org.krost.unidrive.e2e.verify.ManifestEntry
import org.krost.unidrive.e2e.verify.ManifestWriter
import java.nio.file.Files
import java.nio.file.Path

class GoldenStructureBuilder(private val ctx: RunContext) {

    private val nameGen = NameGenerator(
        asciiRatio = ctx.config.general.ascii_name_ratio,
        seed = ctx.runId.hashCode().toLong(),
    )
    private val entries = mutableListOf<ManifestEntry>()
    private val fsType = FsLimits.detectFsType()

    // Set during build() so addEntry can relativize against the root
    private lateinit var rootDir: Path

    fun build(rootDir: Path): List<ManifestEntry> {
        this.rootDir = rootDir
        Files.createDirectories(rootDir)

        buildDocuments(rootDir.resolve("Documents"))
        buildEncodings(rootDir.resolve("Encodings"))
        buildUnicode(rootDir.resolve("Unicode"))
        buildEdgeCases(rootDir.resolve("Edge_Cases"))
        if (MediaGenerator.isAvailable()) {
            buildMedia(rootDir)
        }

        ManifestWriter.write(rootDir.resolve("manifest.sha3-512.jsonl"), entries)
        return entries.toList()
    }

    // ── private builders ──────────────────────────────────────────────────────

    private fun buildDocuments(dir: Path) {
        buildTree(
            dir = dir,
            remainingDepth = ctx.profile.maxDepth,
            filesPerFolder = ctx.profile.filesPerFolder,
            extensions = listOf("pdf", "txt", "md", "docx", "xlsx"),
        )
    }

    private fun buildTree(
        dir: Path,
        remainingDepth: Int,
        filesPerFolder: Int,
        extensions: List<String>,
    ) {
        Files.createDirectories(dir)
        for (i in 0 until filesPerFolder) {
            val ext = extensions[i % extensions.size]
            val name = nameGen.nextFileName(ext)
            if (FsLimits.shouldSkipName(name, fsType)) continue
            val file = dir.resolve(name)
            val content = "Test content for $name — generated by UniDrive 360° at ${ctx.runId}\n".repeat(10)
            Files.writeString(file, content)
            addEntry(file)
        }
        if (remainingDepth > 1) {
            for (s in 0 until 2) {
                val subName = nameGen.nextFolderName()
                if (!FsLimits.shouldSkipName(subName, fsType)) {
                    buildTree(dir.resolve(subName), remainingDepth - 1, filesPerFolder, extensions)
                }
            }
        }
    }

    private fun buildEncodings(dir: Path) {
        Files.createDirectories(dir)
        val encodings = ctx.config.encodings.variants.ifEmpty {
            listOf("UTF-8", "ISO-8859-1", "Shift_JIS", "GB18030", "KOI8-R")
        }
        EncodingSampleFactory.generate(dir, encodings)
        Files.walk(dir).use { stream ->
            stream.filter { Files.isRegularFile(it) }.forEach { file ->
                addEntry(file)
            }
        }
    }

    private fun buildUnicode(dir: Path) {
        Files.createDirectories(dir)

        // All graphic codepoints file
        val allCp = UnicodeCatalog.allGraphicCodepoints()
        val sb = StringBuilder()
        allCp.forEachIndexed { idx, cp ->
            sb.appendCodePoint(cp)
            if ((idx + 1) % 256 == 0) sb.append('\n')
        }
        val cpFile = dir.resolve("all_codepoints_sequential.txt")
        Files.writeString(cpFile, sb.toString())
        addEntry(cpFile)

        // Named unicode folders/files
        data class UnicodeItem(val folder: String, val file: String, val content: String)
        val items = listOf(
            UnicodeItem("日本語のフォルダ", "テスト文書.txt", "Japanese test document\n"),
            UnicodeItem("Ελληνικά_Έγγραφα", "δοκιμή.txt", "Greek test document\n"),
            UnicodeItem("🎵_Emojis_🎬", "🚀_rocket_launch.txt", "Emoji test document\n"),
        )
        for (item in items) {
            if (FsLimits.shouldSkipName(item.folder, fsType)) continue
            if (FsLimits.shouldSkipName(item.file, fsType)) continue
            val subDir = dir.resolve(item.folder)
            Files.createDirectories(subDir)
            val file = subDir.resolve(item.file)
            Files.writeString(file, item.content)
            addEntry(file)
        }
    }

    private fun buildEdgeCases(dir: Path) {
        Files.createDirectories(dir)

        data class EdgeFile(val name: String, val content: String)
        val items = listOf(
            EdgeFile(".hidden_file", "hidden file content\n"),
            EdgeFile("file with  multiple   spaces.txt", "spaces in name\n"),
            EdgeFile("file...with...dots.txt", "dots in name\n"),
            EdgeFile("UPPER_AND_lower_CaSe.TxT", "mixed case name\n"),
            EdgeFile("empty_file_zero_bytes.dat", ""),
        )
        for (item in items) {
            val file = dir.resolve(item.name)
            Files.writeString(file, item.content)
            addEntry(file)
        }
    }

    private fun buildMedia(rootDir: Path) {
        val videoDir = rootDir.resolve("Videos")
        val audioDir = rootDir.resolve("Audio")
        Files.createDirectories(videoDir)
        Files.createDirectories(audioDir)

        val videoFile = videoDir.resolve("test_h265.mp4")
        MediaGenerator.generateTestVideo(videoFile)
        if (Files.exists(videoFile)) addEntry(videoFile)

        val audioFile = audioDir.resolve("test_sine.flac")
        MediaGenerator.generateTestAudio(audioFile)
        if (Files.exists(audioFile)) addEntry(audioFile)
    }

    private fun addEntry(file: Path) {
        val relPath = rootDir.relativize(file).toString().replace('\\', '/')
        val hash = HashVerifier.sha3_512(file)
        val size = Files.size(file)
        val verifyMode = if (relPath.endsWith(".heic")) "size_only" else "full_hash"
        entries += ManifestEntry(
            path = relPath,
            size = size,
            hash = hash,
            verify_mode = verifyMode,
        )
    }
}
