package org.krost.unidrive.internxt

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

class InternxtCryptoTest {
    private val crypto = InternxtCrypto()

    @Test
    fun `decrypt name encrypted by our implementation`() {
        val password = "master-key-folder-42"
        val plaintext = "my-document.pdf"

        val encrypted = crypto.encryptName(plaintext, password)
        val decrypted = crypto.decryptName(encrypted, password)

        assertEquals(plaintext, decrypted)
    }

    @Test
    fun `encrypt produces base64 output with correct structure`() {
        val encrypted = crypto.encryptName("test.txt", "password-123")
        val bytes =
            java.util.Base64
                .getDecoder()
                .decode(encrypted)

        // salt(64) + iv(16) + tag(16) + ciphertext(>=1)
        assertTrue(bytes.size >= 97, "Output must be at least 97 bytes (64+16+16+1)")
    }

    @Test
    fun `different encryptions produce different output (random salt+iv)`() {
        val a = crypto.encryptName("same.txt", "same-password")
        val b = crypto.encryptName("same.txt", "same-password")
        assertNotEquals(a, b, "Random salt/IV should produce different ciphertexts")
    }

    @Test
    fun `decrypt with wrong password throws AEADBadTagException`() {
        val encrypted = crypto.encryptName("secret.txt", "correct-password")
        assertFailsWith<javax.crypto.AEADBadTagException> {
            crypto.decryptName(encrypted, "wrong-password")
        }
    }

    @Test
    fun `encrypt and decrypt with deterministic salt and iv`() {
        val salt = ByteArray(64) { it.toByte() }
        val iv = ByteArray(16) { (it + 100).toByte() }
        val password = "test-key-99"
        val plaintext = "deterministic-test.txt"

        val encrypted = crypto.encryptName(plaintext, password, salt, iv)
        val decrypted = crypto.decryptName(encrypted, password)

        assertEquals(plaintext, decrypted)

        // Same inputs -> same output (deterministic)
        val encrypted2 = crypto.encryptName(plaintext, password, salt, iv)
        assertEquals(encrypted, encrypted2)
    }

    @Test
    fun `BIP39 mnemonic to seed produces 64 bytes`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        val seed = crypto.mnemonicToSeed(mnemonic)
        assertEquals(64, seed.size, "BIP39 seed must be 64 bytes (512 bits)")
    }

    @Test
    fun `BIP39 mnemonic to seed is deterministic`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        val seed1 = crypto.mnemonicToSeed(mnemonic)
        val seed2 = crypto.mnemonicToSeed(mnemonic)
        assertTrue(seed1.contentEquals(seed2))
    }

    @Test
    fun `BIP39 mnemonic to seed matches known test vector`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        val seed = crypto.mnemonicToSeed(mnemonic)
        val expectedHex = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4"
        val actualHex = seed.joinToString("") { "%02x".format(it) }
        assertEquals(expectedHex, actualHex, "Must match BIP39 reference vector")
    }

    @Test
    fun `generate file key produces 32 bytes`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        val seed = crypto.mnemonicToSeed(mnemonic)
        val bucketKey = crypto.deriveBucketKey(seed, "6928426c1a2316b856c9ab81")
        val fileKey = crypto.deriveFileKey(bucketKey, "file-index-abc".toByteArray())
        assertEquals(32, fileKey.size, "File key must be 32 bytes (256 bits)")
    }

    @Test
    fun `decrypt ciphertext produced by JS reference implementation`() {
        // Generated by @internxt/lib aes.encrypt with:
        //   plaintext = "hello-world"
        //   password  = "test-password-123"
        //   salt      = bytes [0..63]  (64 bytes)
        //   iv        = bytes [100..115] (16 bytes)
        //   hops      = 2145
        val jsCiphertext = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P2RlZmdoaWprbG1ub3BxcnNaK2pk75QqGxGIDYSCdulC4ulkVbQkf8/wmM4="
        val decrypted = crypto.decryptName(jsCiphertext, "test-password-123")
        assertEquals("hello-world", decrypted)
    }

    @Test
    fun `encrypt produces output decodable by JS reference implementation`() {
        // Use same deterministic salt/iv as the JS test vector
        val salt = ByteArray(64) { it.toByte() }
        val iv = ByteArray(16) { (it + 100).toByte() }
        val encrypted = crypto.encryptName("hello-world", "test-password-123", salt, iv)

        // Must match the JS-produced ciphertext exactly (same algorithm, same inputs)
        val jsCiphertext = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P2RlZmdoaWprbG1ub3BxcnNaK2pk75QqGxGIDYSCdulC4ulkVbQkf8/wmM4="
        assertEquals(jsCiphertext, encrypted, "JDK and JS must produce identical ciphertext for same inputs")
    }

    @Test
    fun `AES-256-CTR round-trip`() {
        val key = ByteArray(32) { it.toByte() }
        val iv = ByteArray(16) { (it + 10).toByte() }
        val plaintext = "Hello, Internxt storage!".toByteArray()

        val encCipher = crypto.createContentEncryptCipher(key, iv)
        val encrypted = encCipher.doFinal(plaintext)

        val decCipher = crypto.createContentDecryptCipher(key, iv)
        val decrypted = decCipher.doFinal(encrypted)

        assertTrue(plaintext.contentEquals(decrypted))
    }

    @Test
    fun `file key derivation is deterministic`() {
        val mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        val bucket = "test-bucket-id"
        val index = ByteArray(32) { it.toByte() }

        val seed = crypto.mnemonicToSeed(mnemonic)
        val bucketKey = crypto.deriveBucketKey(seed, bucket)
        val key1 = crypto.deriveFileKey(bucketKey, index)
        val key2 = crypto.deriveFileKey(bucketKey, index)

        assertTrue(key1.contentEquals(key2))
        assertEquals(32, key1.size)
    }
}
